### ISSUE TITLE
DB에 내용을 저장할 때 한글이 물음표(?)로 깨져서 저장됩니다

### ISSUE THREAD

**Issue by hyogenie-v** [gae-jang-mo/app#64]
**버그 설명**
DB에 한글이 깨져서 저장됩니다

**스크린샷**
![image](https://user-images.githubusercontent.com/25656510/71230723-1968fc80-232e-11ea-89eb-9b0432bccfc9.png)
![image](https://user-images.githubusercontent.com/25656510/71230731-2128a100-232e-11ea-9021-07a3c5dc8d74.png)

**Comment by JunHoPark93** [comment]
utf8 설정으로 해결
